### ISSUE TITLE
how to use please?

### ISSUE THREAD

**Issue by genru** [yhb241/pull-to-load-more#1]
Hi,

thanks public such a great lib, which is what i am looking for. but I spend a lot time to find how to use it, if you can write a bit usage instruction would be helpful for user.

I have tried
```
PullToLoadMore();
or
new PullToLoadMore()
```
but no lucky, i always get js error message in browser console.

**Comment by genru** [comment]
```
new PullToLoadMore()
```
get error 
```
Uncaught TypeError: PullToLoadMore is not a constructor
```

**Comment by herbertyoung** [comment]
Thanks for your comment. I will update the README as soon as possible.

**Comment by herbertyoung** [comment]
> ```
> new PullToLoadMore()
> ```
> get error
> 
> ```
> Uncaught TypeError: PullToLoadMore is not a constructor
> ```

Maybe you didn't include the library file.
```html
<script src="PullToLoadMore.js"></script>
```

**Comment by genru** [comment]
Yes, I have included it(build/PullToLoadMore.js)
```
      <script src="/assets/scripts/PullToLoadMore.js"></script>
      <script src="/assets/scripts/app.js"></script>
```
in app.js
```
document.addEventListener('DOMContentLoaded', () => {
...
    var a = new PullToLoadMore();     // <---- failed here
    a.init({onLoadMore: function() {
      console.info('onLoadMore');
    }});
...
});
```
unfortunately, it not work. with error `Uncaught TypeError: PullToLoadMore is not a constructor`

**Comment by genru** [comment]
I resolved it by removing `export default ` at line 81 PullToLoadMore.js.

I am not a js expert, unable to figure out why. Perhaps it's a thread for you to fix it.

**Comment by herbertyoung** [comment]
Thanks for your clues. I will resolve this problem.
You can use it like this temporarily:
```Javascript
new PullToLoadMore.default();
```

**Comment by herbertyoung** [comment]
`pull-to-load-more` 1.0.1 has been released.
Now you can use it like this:
```Javascript
new PullToLoadMore();
```
Thank you again for your comments.

**Comment by genru** [comment]
great! thanks

**Comment by herbertyoung** [comment]
README has been updated.
